### ISSUE TITLE
Bug Report: Failed to Complete Normal Setup

### ISSUE THREAD

**Issue by andrew2zhao** [VACenter/VACenter#114] opened 2022-08-15 07:25 UTC
**Describe the bug**
Error showing "An error occured during setup! Check the console."

**To Reproduce**
1. Accept Analytics
2. Input Airline Name
3. Input Airline Code
4. Create default account
5. Review Settings and hit "Finish Setup"
6. Confirm again with pop-up "Setup"

**Expected behavior**
Successful completion of setup process.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome

**Comment by Sam-Neale** [comment] 2022-08-15 07:31
Resolved in commit 15c03f1cc07c9a57a79de7b205604da4887d1e52

Issue appears to be caused by the development unit's mysql version accepting defaults for the routes gate column, whilst prod doesn't. 

This caused the database generation to fail, which caused setup to fail.

This has been resolved by removing the default for that column and using null.

caf70b52f8f928f76f0ffe29435b25eb74835910 resolved this issue for other columns. Originally gate was the problematic one.

This fix is not considered its own beta, and should be git pulled.

**Closed by Sam-Neale** 2022-08-15 07:31 UTC
Labels: bug
